import api from './axios';
export const getAdminUsers       = (params) => api.get('/admin/users', { params });
export const getAdminUser        = (id) => api.get(`/admin/users/${id}`);
export const createUser          = (data) => api.post('/admin/users', data);
export const updateUser          = (id, data) => api.put(`/admin/users/${id}`, data);
export const toggleUserActive    = (id) => api.patch(`/admin/users/${id}/toggle-active`);
export const changeUserRole      = (id, role) => api.patch(`/admin/users/${id}/role`, null, { params: { role } });
export const deleteUser          = (id) => api.delete(`/admin/users/${id}`);
export const createAdmin         = (data) => api.post('/admin/admins', data);
export const getAdminDashboard   = () => api.get('/admin/dashboard');
export const getUserTransactions = (id, params) => api.get(`/admin/users/${id}/transactions`, { params });
export const getUserLoans        = (id) => api.get(`/admin/users/${id}/loans`);
export const getUserDebts        = (id) => api.get(`/admin/users/${id}/debts`);
export const getUserSavingGoals  = (id) => api.get(`/admin/users/${id}/saving-goals`);
