import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications',
    viewProfile: 'View profile',
    logout: 'Sign out',
    menu: 'Menu',
    admin: 'Admin',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    budget: 'Budget',
    savings: 'Savings',
    goals: 'Goals',
    loans: 'Loans',
    debts: 'Debts',
    forecast: 'Forecast',
    profile: 'Profile',
    adminDashboard: 'Admin Dashboard',
    users: 'Users',
    stochy: 'STOCHY',

    // DashboardPage
    'Tableau de bord': 'Dashboard',
    'Maîtrisez vos finances avec des indicateurs clairs et un design inspiré.': 'Master your finances with clear indicators and inspired design.',
    'Visualisez vos revenus, dépenses, budgets et objectifs dans un environnement sombre, moderne et fluide.': 'Visualize your income, expenses, budgets and goals in a dark, modern and fluid environment.',
    'Solde actuel': 'Current Balance',
    'Solde global disponible ce mois.': 'Global balance available this month.',
    'Revenus mensuels': 'Monthly Income',
    'Voir l\'évolution de vos revenus récents.': 'See the evolution of your recent income.',
    'Vue rapide': 'Quick View',
    'Sélectionnez la période pour mettre à jour vos analyses.': 'Select the period to update your analyses.',
    'Revenus': 'Income',
    'Dépenses': 'Expenses',
    'Épargne': 'Savings',
    'Solde net': 'Net balance',
    'Revenus vs Dépenses (6 derniers mois)': 'Income vs Expenses (last 6 months)',
    'Dépenses par catégorie': 'Expenses by category',
    'Aucune dépense enregistrée pour cette période.': 'No expenses recorded for this period.',
    'État des budgets': 'Budget status',
    'Aucun budget défini pour cette période.': 'No budget defined for this period.',
    'Objectifs d\'épargne actifs': 'Active savings goals',
    'Aucun objectif d\'épargne actif.': 'No active savings goals.',
    'Alertes actives': 'Active alerts',

    // TransactionsPage
    'Rechercher...': 'Search...',
    'Tous les types': 'All types',
    'Toutes les catégories': 'All categories',
    'Ajouter': 'Add',
    'Aucune transaction': 'No transactions',
    'Commencez par ajouter des entrées ou des dépenses.': 'Start by adding entries or expenses.',
    'Titre': 'Title',
    'Montant': 'Amount',
    'Date': 'Date',
    'Type': 'Type',
    'Catégorie': 'Category',
    'Type de dépense': 'Expense type',
    'Type de revenu': 'Income type',
    'Portée': 'Scope',
    'Récurrent': 'Recurring',
    'Traiter automatiquement à la date': 'Process automatically on date',
    'Fréquence': 'Frequency',
    'Jour de récurrence (1-28)': 'Recurrence day (1-28)',
    'Notes': 'Notes',
    'Annuler': 'Cancel',
    'Enregistrer': 'Save',
    'Nouvelle transaction': 'New transaction',
    'Modifier la transaction': 'Edit transaction',
    'Importer des transactions via CSV': 'Import transactions via CSV',
    'Téléchargez un fichier CSV contenant les colonnes suivantes dans l\'ordre :': 'Download a CSV file containing the following columns in order:',
    'Cliquez pour choisir un fichier ou déposez-le ici': 'Click to choose a file or drag it here',
    'Dépense': 'Expense',
    'Revenu': 'Income',
    'Normal': 'Normal',
    'Dette': 'Debt',
    'Prêt': 'Loan',
    'Salaire': 'Salary',
    'Business': 'Business',
    'Investissement': 'Investment',
    'Aide sociale': 'Social aid',
    'Pension': 'Pension',
    'Autre': 'Other',
    'Montant fixe': 'Fixed amount',
    'Pourcentage': 'Percentage',
    'Manuel': 'Manual',
    'Quotidien': 'Daily',
    'Hebdomadaire': 'Weekly',
    'Mensuel': 'Monthly',
    'Trimestriel': 'Quarterly',
    'Annuel': 'Annually',
    'Personnel': 'Personal',
    'Familial': 'Family',
    'Homme': 'Male',
    'Femme': 'Female',
    'Non spécifié': 'Unspecified',
    'Marié(e)': 'Married',
    'Célibataire': 'Single',
    'Divorcé(e)': 'Divorced',
    'Employé(e)': 'Employed',
    'Sans emploi': 'Unemployed',
    'Étudiant(e)': 'Student',
    'Étudiant': 'Student',
    'Auto': 'Auto',
    'Consommation': 'Consumer',
    'Immobilier': 'Mortgage',
    'En cours': 'Ongoing',
    'Partiellement remboursé': 'Partially repaid',
    'Réglé': 'Settled',
    'Automatique': 'Automatic',
    'Mixte': 'Mixed',
    'Attention': 'Warning',
    'Dépassé': 'Exceeded',
    'Administrateur': 'Administrator',
    'Utilisateur Premium': 'Premium User',

    // BudgetsPage
    'Dupliquer': 'Duplicate',
    'Définir un budget': 'Set a budget',
    'Limite :': 'Limit:',
    'Restant :': 'Remaining:',
    'Alerte à': 'Alert at',
    'Aucun budget défini': 'No budget defined',
    'Prenez le contrôle de vos finances en fixant des limites par catégorie.': 'Take control of your finances by setting limits per category.',
    'Configurer un budget': 'Set up a budget',
    'Budget Global (Toutes catégories)': 'Global Budget (All categories)',
    'Montant limite': 'Limit amount',
    'Seuil d\'alerte (%)': 'Alert threshold (%)',
    'Seuil obligatoire': 'Threshold required',
    'Dupliquer les budgets': 'Duplicate budgets',
    'Copiez les budgets d\'un mois précédent vers le mois en cours ({month}/{year}).': 'Copy budgets from a previous month to the current month.',
    'Copiez les budgets d\'un mois précédent vers le mois en cours': 'Copy budgets from a previous month to the current month',
    'Mois source': 'Source month',
    'Année source': 'Source year',
    'Voulez-vous vraiment supprimer ce budget ?': 'Are you sure you want to delete this budget?',
    'Dépensé :': 'Spent:',
    'Restant': 'Remaining',

    // SavingsPage
    'Épargne totale': 'Total savings',
    'Alloué aux objectifs': 'Allocated to goals',
    'Solde libre d\'utilisation': 'Available balance',
    'Règles d\'épargne automatique': 'Automatic savings rules',
    'Ajouter une règle': 'Add a rule',
    'Aucune règle configurée': 'No rules configured',
    'Configurez une règle d\'épargne automatique pour économiser dès la réception d\'un revenu.': 'Set up an automatic savings rule to save as soon as you receive income.',
    'Configurer une règle d\'épargne': 'Configure a savings rule',
    'Mode d\'épargne': 'Savings mode',
    'Pourcentage (%)': 'Percentage (%)',
    'Appliquer à tous les revenus': 'Apply to all income',
    'Revenus ciblés :': 'Targeted income:',
    'Jour de récurrence': 'Recurrence day',
    'Sauvegarder': 'Save',
    'Voulez-vous vraiment supprimer cette règle d\'épargne ?': 'Are you sure you want to delete this savings rule?',
    'des revenus': 'of income',
    'Appliqué à tous les revenus': 'Applied to all income',
    'Sur :': 'On:',
    'Fréquence :': 'Frequency:',

    // GoalsPage
    'Suivi des Objectifs d\'Épargne': 'Savings Goals Tracking',
    'Nouvel objectif': 'New goal',
    'Objectif :': 'Goal:',
    'Date cible :': 'Target date:',
    'Aucune': 'None',
    'Mode :': 'Mode:',
    'Épargne recommandée :': 'Recommended savings:',
    '/ mois': '/ month',
    'Contribuer': 'Contribute',
    'Aucun objectif': 'No goals',
    'Fixez-vous un but (Ex. fonds d\'urgence, vacances) pour orienter votre épargne.': 'Set a goal (e.g. emergency fund, vacation) to guide your savings.',
    'Créer un objectif d\'épargne': 'Create a savings goal',
    'Nom de l\'objectif': 'Goal name',
    'Description (optionnel)': 'Description (optional)',
    'Montant cible': 'Target amount',
    'Date cible': 'Target date',
    'Mode de financement': 'Funding mode',
    'Notes / Conditions': 'Notes / Conditions',
    'Contribuer à': 'Contribute to',
    'Date de contribution': 'Contribution date',

    // LoansPage
    'Capital': 'Capital',
    'Intérêts': 'Interest',
    'Date d\'échéance': 'Due date',
    'Suivi des Emprunts & Dettes Financières': 'Monitoring of Loans & Financial Debts',
    'Nouveau prêt': 'New loan',
    'Régler': 'Settle',
    'Remboursé :': 'Repaid:',
    'Capital restant :': 'Remaining capital:',
    'Total payé (Intérêts incl.)': 'Total paid (Interest incl.)',
    'Prochaine échéance': 'Next due date',
    'Aucun prêt actif': 'No active loans',
    'Ajoutez vos emprunts pour suivre vos échéanciers de remboursement.': 'Add your loans to track your repayment schedules.',
    'Créer un emprunt / prêt financier': 'Create a borrowing / financial loan',
    'Nom du créancier': 'Lender name',
    'Type de prêt': 'Loan type',
    'Date de début': 'Start date',
    'Capital initial': 'Initial capital',
    'Mensualité': 'Monthly installment',
    'Taux d\'intérêt (%)': 'Interest rate (%)',
    'Durée (mois)': 'Duration (months)',
    'Calculer & Générer l\'échéancier': 'Calculate & Generate schedule',
    'Tableau d\'amortissement —': 'Amortization table —',
    'Capital Emprunté': 'Borrowed Capital',
    'Intérêts Remboursés': 'Interest Repaid',
    'Reste à payer': 'Remaining to pay',
    'Fermer': 'Close',

    // DebtsPage
    'Dettes actives (Argent prêté)': 'Active Debts (Lent money)',
    'Prêter de l\'argent': 'Lend money',
    'Total prêté': 'Total lent',
    'Reste à recouvrer': 'Remaining to recover',
    'Date de prêt :': 'Loan date:',
    'Date prévue :': 'Expected date:',
    'Remboursements reçus': 'Repayments received',
    'Enregistrer un remboursement': 'Record a repayment',
    'Aucune dette': 'No debts',
    'Ajoutez les prêts accordés à vos proches pour ne plus oublier d\'être remboursé.': 'Add loans granted to your relatives to never forget to be repaid.',
    'Enregistrer une dette (Argent prêté)': 'Record a debt (Lent money)',
    'Nom de l\'emprunteur / débiteur': 'Borrower / Debtor name',
    'Montant prêté': 'Lent amount',
    'Date du prêt': 'Loan date',
    'Date de remboursement prévue': 'Expected repayment date',
    'Remboursement de': 'Repayment from',
    'Montant reçu': 'Amount received',
    'Date du versement': 'Payment date',
    'Notes (Mode de versement...)': 'Notes (Payment method...)',
    'Valider le versement': 'Validate payment',

    // ForecastPage
    'Prévisions Financières Prédictives': 'Predictive Financial Forecasts',
    'Simulation de trésorerie sur la base de vos revenus et dépenses récurrents.': 'Cash flow simulation based on your recurring income and expenses.',
    'Prochains': 'Next',
    'mois': 'months',
    'Évolution prévisionnelle de la trésorerie': 'Forecast evolution of cash flow',
    'Solde projeté': 'Projected balance',
    'Conseils et optimisations intelligents': 'Smart tips and optimizations',
    'Aucune alerte ou conseil pour le moment. Votre situation financière semble saine et stable !': 'No alerts or advice for now. Your financial situation seems healthy and stable!',
    'Déficits ou anomalies de trésorerie détectés': 'Deficits or cash flow anomalies detected',
    'Solde négatif projeté à': 'Negative balance projected at',
    'Aucun déficit de trésorerie n\'est à prévoir sur cette période.': 'No cash flow deficit is expected over this period.',

    // ProfilePage
    'Informations personnelles & Préférences': 'Personal Information & Preferences',
    'Prénom': 'First name',
    'Nom': 'Last name',
    'Téléphone': 'Phone',
    'Date de naissance': 'Birth date',
    'Genre': 'Gender',
    'Situation professionnelle': 'Professional status',
    'Situation familiale': 'Family status',
    'Pays': 'Country',
    'Région / Gouvernorat': 'Region / State',
    'Délégation / Municipalité': 'City / Municipality',
    'Rue': 'Street',
    'Numéro': 'Number',
    'Enregistrer les modifications': 'Save changes',
    'Sécurité & Mot de passe': 'Security & Password',
    'Mot de passe actuel': 'Current password',
    'Nouveau mot de passe': 'New password',
    'Confirmer le nouveau mot de passe': 'Confirm new password',
    'Modifier le mot de passe': 'Change password',

    // Category names (for graphs & lists)
    'Alimentation': 'Food',
    'Logement': 'Housing',
    'Transport': 'Transportation',
    'Santé': 'Health',
    'Loisirs': 'Leisure',
    'Éducation': 'Education',
    'Vêtements': 'Clothing',
    'Abonnements': 'Subscriptions',
    'Famille': 'Family',
    'Dons': 'Gifts',
    'Autres': 'Others',
    'Freelance': 'Freelance',
    'Autres revenus': 'Other Income',

    // Success/error/form validations common
    'Titre obligatoire': 'Title required',
    'Montant obligatoire': 'Amount required',
    'Date obligatoire': 'Date required',
    'Fréquence obligatoire': 'Frequency required',
    'Créancier obligatoire': 'Lender required',
    'Capital obligatoire': 'Capital required',
    'Mensualité obligatoire': 'Installment required',
    'Taux obligatoire': 'Rate required',
    'Durée obligatoire': 'Duration required',
    'Nom obligatoire': 'Name required',
    'Nom de l\'emprunteur obligatoire': 'Borrower name required',
    'Les mots de passe ne correspondent pas': 'Passwords do not match',
    'Doit être supérieur à 0': 'Must be greater than 0',

    // Landing Page
    'Accueil': 'Home',
    'Services': 'Services',
    'Avis': 'Reviews',
    'Contact': 'Contact',
    'Gestion intelligente de votre argent': 'Smart management of your money',
    'Prenez le contrôle de votre situation financière en toute simplicité.': 'Take control of your financial situation with ease.',
    'Nos Services': 'Our Services',
    'Découvrez les fonctionnalités puissantes de STOCHY': 'Discover the powerful features of STOCHY',
    'Tableau de Bord Holistique': 'Holistic Dashboard',
    'Une vue d\'ensemble claire de vos soldes, transactions et analyses graphiques interactives.': 'A clear overview of your balances, transactions and interactive graphical analyses.',
    'Budgets Précis': 'Precise Budgets',
    'Fixez des limites par catégorie pour maîtriser vos dépenses et éviter les mauvaises surprises.': 'Set limits by category to control your expenses and avoid bad surprises.',
    'Objectifs Stimulants': 'Motivating Goals',
    'Visualisez vos progrès vers vos projets et économisez de manière ciblée et méthodique.': 'Visualize your progress towards your projects and save in a targeted and methodical way.',
    'Prévisions Futuristes': 'Futuristic Forecasts',
    'Simulez votre trésorerie future grâce à nos algorithmes prédictifs basés sur vos récurrences.': 'Simulate your future cash flow using our predictive algorithms based on your recurrences.',
    'Ce que disent nos utilisateurs': 'What our users say',
    'Des milliers de personnes font confiance à STOCHY pour gérer leur argent au quotidien.': 'Thousands of people trust STOCHY to manage their money daily.',
    'Contactez-nous': 'Contact Us',
    'Une question ou une suggestion ? Notre équipe est là pour vous aider.': 'A question or a suggestion? Our team is here to help.',
    'Votre nom': 'Your name',
    'Votre message': 'Your message',
    'Envoyer le message': 'Send message',
    'Message envoyé avec succès !': 'Message sent successfully!',
    'Tous droits réservés.': 'All rights reserved.',
  },
  fr: {
    notifications: 'Notifications',
    markAllRead: 'Tout marquer lu',
    noNotifications: 'Aucune notification',
    viewProfile: 'Voir profil',
    logout: 'Se déconnecter',
    menu: 'Menu',
    admin: 'Admin',
    dashboard: 'Tableau de bord',
    transactions: 'Transactions',
    budget: 'Budget',
    savings: 'Épargne',
    goals: 'Objectifs',
    loans: 'Prêts',
    debts: 'Dettes',
    forecast: 'Prévisions',
    profile: 'Profil',
    adminDashboard: 'Tableau de bord Admin',
    users: 'Utilisateurs',
    stochy: 'STOCHY'
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('stochy_lang') || 'fr'; } catch { return 'fr'; }
  });

  const setLanguage = (l) => {
    setLang(l);
    try { localStorage.setItem('stochy_lang', l); } catch (e) {}
  };

  const t = (key) => {
    if (translations[lang] && translations[lang][key] !== undefined) {
      return translations[lang][key];
    }
    return key;
  };

  return <LanguageContext.Provider value={{ lang, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() { return useContext(LanguageContext); }

export default LanguageContext;
